### ISSUE TITLE
证书私钥没有记下来

### ISSUE THREAD

**Issue by kuretru** [Sneezry/SSL.MD-Support#1]
我于20号签了第1张证书，一切顺利，第2张证书时，你网页的ns验证通过没有问题，但是签发证书时，发生错误，邮箱收到邮件  
{"identifier":{"type":"dns","value":"xxxx.com"},"status":"invalid","expires":"2016-09-27T10:50:57Z","challenges":[{"type":"http-01","status":"pending","uri":"https:\/\/acme-v01.api.letsencrypt.org\/acme\/challenge\/S9kkJ6iBtKhQBaAMjC0srNJjdeRGjOUVDY5TMWu-qtg\/269411193","token":"fpAIJrQ8BhDzI3BaKgPWbURrMOzH07F7iK0TuGGSmn0"},{"type":"dns-01","status":"invalid","error":{"type":"urn:acme:error:connection","detail":"DNS problem: SERVFAIL looking up TXT for _acme-challenge.dorm.i5zhen.com","status":400},"uri":"https:\/\/acme-v01.api.letsencrypt.org\/acme\/challenge\/S9kkJ6iBtKhQBaAMjC0srNJjdeRGjOUVDY5TMWu-qtg\/269411194","token":"Dl9BMNIZewNs9blMFB1kTOIs0aDtpEnv5JV1kQEnNRE","keyAuthorization":"Dl9BMNIZewNs9blMFB1kTOIs0aDtpEnv5JV1kQEnNRE.q5u-yFORx3z1x-k6DjXpNKFQjLI6oF-IK61urwxviSA"},{"type":"tls-sni-01","status":"pending","uri":"https:\/\/acme-v01.api.letsencrypt.org\/acme\/challenge\/S9kkJ6iBtKhQBaAMjC0srNJjdeRGjOUVDY5TMWu-qtg\/269411195","token":"QcdrI7GE-85DxGOAYf5aCFeISGrUV8KhqL1hQQQ0vC8"}],"combinations":[[2],[1],[0]]}  
20号时，我在控制面板删除了该域名，并删除了第一次签发时保存的私钥，第二次签发成功，但是私钥缺没有再次提供。

**Comment by Sneezry** [comment]
通过SSL.MD在线生成CSR后会自动签发证书，并显示私钥，但如果通过上传CSR则不会显示私钥。如果确实需要在线生成CSR并由SSL.MD提供私钥，可以通过点击dashboard域名列表中的CSR链接进入CSR上传页面，并点击Generate按钮，之后会显示私钥并重新签发证书。私钥只会在生成CSR后显示一次，之后无法在任何地方看到，SSL.MD也不会在任何地方对其进行保存，但是生成的CSR会保存在数据库中，通过Re-issue重新签发域名时会使用保存的CSR，重新签发的证书私钥不变。

**Comment by kuretru** [comment]
的确，第一次生成证书的时候我手动生成了CSR，现在回想起来是误点击了Generate，由服务端生成了CSR，导致后续网页出现CSR提示保存。

**Comment by Sneezry** [comment]
签发证书的过程对于没接触过的用户来说非常繁琐，很多用户根本分不清CSR、KEY、CRT都是什么东西，我希望能帮助用户签发证书的同时淡化这些概念，不必让用户花费时间去研究明白那些东西，同时又能保证证书的安全性。希望能获取到更多用户使用过程中造成困惑的地方，以便进行改进。感谢反馈。

**Comment by kuretru** [comment]
建议Upload CSR的按钮做成绿色，生成的按钮做成暗色调，引导用户尽量使用自己生成的CSR，很多时候，左边的按钮是确定，右边的按钮是取消，我就是粘贴完CSR手快点了生成的按钮。

**Comment by Sneezry** [comment]
赞，这就去修改

在 2016年9月22日 下午9:12，呉真 notifications@github.com写道：
